'use client';

import { useState, useEffect } from 'react';
import { seoService, type SEOConfig } from '@/lib/api/seo.service';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { Loader2, Save, Settings, FileText, MessageSquare } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';
import { useTranslations } from 'next-intl';

export default function SEOConfigPage() {
  const [configs, setConfigs] = useState<SEOConfig[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<string | null>(null);
  const { toast } = useToast();
  const t = useTranslations('boMisc');

  useEffect(() => {
    loadConfigs();
  }, []);

  const loadConfigs = async () => {
    try {
      setLoading(true);
      const data = await seoService.listConfigs();
      setConfigs(data);
    } catch (error: any) {
      toast({
        title: t('seoError'),
        description: error.message || t('seoErrorLoadingConfigs'),
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async (config: SEOConfig) => {
    try {
      setSaving(config.entityType);
      await seoService.upsertConfig({
        entityType: config.entityType,
        metaTitleTemplate: config.metaTitleTemplate,
        metaDescriptionTemplate: config.metaDescriptionTemplate,
        qaPrompt: config.qaPrompt,
        availableVariables: config.availableVariables,
        autoGenerate: config.autoGenerate,
        generateOnCreate: config.generateOnCreate,
        generateOnUpdate: config.generateOnUpdate,
      });

      toast({
        title: t('seoSavedTitle'),
        description: t('seoConfigSavedFor', { entityType: config.entityType }),
      });

      await loadConfigs();
    } catch (error: any) {
      toast({
        title: t('seoError'),
        description: error.message || t('seoErrorSaving'),
        variant: 'destructive',
      });
    } finally {
      setSaving(null);
    }
  };

  const updateConfig = (entityType: string, field: string, value: any) => {
    setConfigs((prev) =>
      prev.map((c) => (c.entityType === entityType ? { ...c, [field]: value } : c))
    );
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="h-8 w-8 animate-spin" />
      </div>
    );
  }

  const entityTypes = [
    { value: 'event', label: t('seoEventos'), icon: '🏃' },
    { value: 'competition', label: t('seoCompeticiones'), icon: '🏔️' },
    { value: 'post', label: t('seoPosts'), icon: '📝' },
    { value: 'home', label: t('seoPaginaPrincipal'), icon: '🏠' },
    { value: 'events-list', label: t('seoListadoEventos'), icon: '📋' },
  ];

  return (
    <div className="container mx-auto py-8 px-4">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">⚙️ {t('seoConfigTitle')}</h1>
        <p className="text-muted-foreground">
          {t('seoConfigSubtitle')}
        </p>
      </div>

      <Tabs defaultValue="event" className="space-y-4">
        <TabsList className="grid w-full grid-cols-5">
          {entityTypes.map((type) => (
            <TabsTrigger key={type.value} value={type.value}>
              {type.icon} {type.label}
            </TabsTrigger>
          ))}
        </TabsList>

        {entityTypes.map((type) => {
          const config = configs.find((c) => c.entityType === type.value);
          if (!config) return null;

          return (
            <TabsContent key={type.value} value={type.value} className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Settings className="h-5 w-5" />
                    {t('seoGeneralConfig')}
                  </CardTitle>
                  <CardDescription>
                    {t('seoGeneralConfigDesc')}
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="space-y-0.5">
                      <Label htmlFor={`auto-${type.value}`}>{t('seoAutoGenerate')}</Label>
                      <p className="text-sm text-muted-foreground">
                        {t('seoAutoGenerateDesc')}
                      </p>
                    </div>
                    <Switch
                      id={`auto-${type.value}`}
                      checked={config.autoGenerate}
                      onCheckedChange={(checked) =>
                        updateConfig(type.value, 'autoGenerate', checked)
                      }
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div className="space-y-0.5">
                      <Label htmlFor={`onCreate-${type.value}`}>{t('seoGenerateOnCreate')}</Label>
                      <p className="text-sm text-muted-foreground">
                        {t('seoGenerateOnCreateDesc')}
                      </p>
                    </div>
                    <Switch
                      id={`onCreate-${type.value}`}
                      checked={config.generateOnCreate}
                      onCheckedChange={(checked) =>
                        updateConfig(type.value, 'generateOnCreate', checked)
                      }
                      disabled={!config.autoGenerate}
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div className="space-y-0.5">
                      <Label htmlFor={`onUpdate-${type.value}`}>{t('seoGenerateOnUpdate')}</Label>
                      <p className="text-sm text-muted-foreground">
                        {t('seoGenerateOnUpdateDesc')}
                      </p>
                    </div>
                    <Switch
                      id={`onUpdate-${type.value}`}
                      checked={config.generateOnUpdate}
                      onCheckedChange={(checked) =>
                        updateConfig(type.value, 'generateOnUpdate', checked)
                      }
                      disabled={!config.autoGenerate}
                    />
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <FileText className="h-5 w-5" />
                    {t('seoMetaTagsTemplates')}
                  </CardTitle>
                  <CardDescription>
                    {t('seoMetaTagsTemplatesDesc', { name: '{name}', location: '{location}', distance: '{distance}' })}
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor={`title-${type.value}`}>{t('seoMetaTitleTemplate')}</Label>
                    <Input
                      id={`title-${type.value}`}
                      value={config.metaTitleTemplate || ''}
                      onChange={(e) =>
                        updateConfig(type.value, 'metaTitleTemplate', e.target.value)
                      }
                      placeholder={t('seoTitleTemplatePlaceholder')}
                    />
                    <p className="text-xs text-muted-foreground">
                      {t('seoMaxRecommended60')}
                    </p>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor={`desc-${type.value}`}>{t('seoMetaDescriptionTemplate')}</Label>
                    <Textarea
                      id={`desc-${type.value}`}
                      value={config.metaDescriptionTemplate || ''}
                      onChange={(e) =>
                        updateConfig(type.value, 'metaDescriptionTemplate', e.target.value)
                      }
                      placeholder={t('seoDescTemplatePlaceholder')}
                      rows={3}
                    />
                    <p className="text-xs text-muted-foreground">
                      {t('seoMaxRecommended155')}
                    </p>
                  </div>

                  <div>
                    <Label className="mb-2">{t('seoAvailableVariables')}</Label>
                    <div className="flex flex-wrap gap-2 mt-2">
                      {config.availableVariables?.map((variable: string) => (
                        <Badge key={variable} variant="secondary">
                          {`{${variable}}`}
                        </Badge>
                      ))}
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <MessageSquare className="h-5 w-5" />
                    {t('seoQaPromptTitle')}
                  </CardTitle>
                  <CardDescription>
                    {t('seoQaPromptDesc')}
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor={`prompt-${type.value}`}>{t('seoPromptTemplate')}</Label>
                    <Textarea
                      id={`prompt-${type.value}`}
                      value={config.qaPrompt || ''}
                      onChange={(e) => updateConfig(type.value, 'qaPrompt', e.target.value)}
                      placeholder={t('seoQaPromptPlaceholder')}
                      rows={15}
                      className="font-mono text-sm"
                    />
                    <p className="text-xs text-muted-foreground">
                      {t('seoPromptTemplateHint')}
                    </p>
                  </div>
                </CardContent>
              </Card>

              <div className="flex justify-end">
                <Button
                  onClick={() => handleSave(config)}
                  disabled={saving === type.value}
                  size="lg"
                >
                  {saving === type.value ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      {t('guardando')}
                    </>
                  ) : (
                    <>
                      <Save className="mr-2 h-4 w-4" />
                      {t('seoGuardarConfiguracion')}
                    </>
                  )}
                </Button>
              </div>
            </TabsContent>
          );
        })}
      </Tabs>
    </div>
  );
}
